function [] = SaveSurfObj(output, nodes, faces, nodenormals)
%SAVEEMBGRIDTOVTK Summary of this function goes here
%   Detailed explanation goes here

% Check filepath's extension
[~, ~, ext] = fileparts(output);
if (~strcmp(ext,'.obj'))
    error('Filename should have .obj extension');
end

% Check nodes and elems format
[nodes_num, nodes_dims] = size(nodes);
elems_num = size(faces,1);

if nargin < 4, nodenormals = nodes; end

if (nodes_num == 0)
    error('Nodes list is empty');
elseif (nodes_dims < 3)
    error('Unsupported nodes dimensions. Required nodes with dimensions 3')
end

if (elems_num == 0)
    error('Elements list is empty')
end

format long g;

% Open output file and write header
fileID = fopen(output,'w');
fprintf('Writing to OBJ file: %s ...',output);

fprintf(fileID,'####\n');
fprintf(fileID,'#\n# OBJ File Generated by SaveSurfObj.m\n#\n');
fprintf(fileID,'####\n# Object mesh\n#\n');
fprintf(fileID,'# Vertices: %d\n',nodes_num);
fprintf(fileID,'# Faces: %d\n',elems_num);
fprintf(fileID,'#\n####\n');

% Write nodes
for nn = 1:nodes_num
    fprintf(fileID,'vn %10.15f %10.15f %10.15f\n', nodenormals(nn,:));
    fprintf(fileID,'v %10.15f %10.15f %10.15f\n', nodes(nn,:));
end
fprintf(fileID,'# %d vertices, %d vertices normals\n\n',nodes_num,nodes_num);

% Write elements
for el_id = 1:elems_num
    fprintf(fileID,'f %d//%d %d//%d %d//%d\n',faces(el_id,1),faces(el_id,1), faces(el_id,2),faces(el_id,2), faces(el_id,3),faces(el_id,3));
end

fprintf(fileID,'# %d faces, 0 coords texture\n\n# End of File\n',elems_num);


% Close output file
fclose(fileID);

fprintf(' DONE\n');

end

