import os 
import numpy as np
import argparse
import meshio
from scipy.spatial.distance import cdist

parser = argparse.ArgumentParser(description="Options")
parser.add_argument('--meshHeart',type=str, required=True, help='path to data')
parser.add_argument('--meshOnHeart',type=str, required=True, help='path to data')
parser.add_argument('--meshScaffold',type=str, required=True, help='path to data')
parser.add_argument('--outPath',type=str, required=True, help='path to data')
parser.add_argument('--heartSurface', action='store_true', help='path to data')
parser.add_argument('--scaffoldSurface', action='store_true', help='path to data')
args = parser.parse_args()

meshHeart = meshio.read(args.meshHeart)
meshOnHeart = meshio.read(args.meshOnHeart)
meshScaffold = meshio.read(args.meshScaffold)
scaffoldPoints = meshScaffold.points
heartPoints = meshHeart.points
lmsDiff = {}
for key in meshOnHeart.point_data.keys():
    if not "all" in key and ("LM" in key or "lm" in key) and not "lms" in key:
        B = meshOnHeart.points[np.where(meshOnHeart.point_data[key]==1)[0][0],:]
        A = meshScaffold.points[np.where(meshScaffold.point_data[key]==1)[0][0],:]
        lmsDiff[key] = B - A

nnl=15
if args.heartSurface:
    heartCellShape = "triangle"
else:
    heartCellShape = "tetra"

if args.scaffoldSurface:
    scaffoldCellShape = "quad"
else:
    scaffoldCellShape = "tetra"

#Write Model in inp
with open(args.outPath, 'w') as f:
    f.write("*Heading\n")
    f.write("** Job name: modelJob Model name: model\n")
    f.write("** Generated by: Abaqus/CAE 2020\n")
    f.write("*Preprint, echo=NO, model=NO, history=NO, contact=NO\n")
    f.write("**\n** PARTS\n**\n")
    #! Inp mush start from 1 in node list and of course in elems

    #HEART
    f.write("*Part, name=HEART\n")
    f.write("*Node\n")
    for idx, n in enumerate(meshHeart.points):
        f.write("{0:d}, {1:.15f}, {2:.15f}, {3:.15f}\n".format(idx+1, n[0], n[1], n[2]))
    if args.heartSurface:
        f.write("*Element, type=S3\n")
        for idx, el in enumerate(meshHeart.cells_dict[heartCellShape]):
            f.write("{0:d}, {1:d}, {2:d}, {3:d}\n".format(idx+1, el[0]+1, el[1]+1, el[2]+1))
        f.write("*Elset, elset=ALL_HEART, generate\n")
        f.write("1, {}, 1\n".format(meshHeart.cells_dict[heartCellShape].shape[0]))
        f.write("** Section: Section_HEART\n")
        f.write("*Shell Section, elset=ALL_HEART, material=MATERIAL_HEART\n")
        f.write("0.2, 5\n")
    else:
        f.write("*Element, type=C3D4\n")
        for idx, el in enumerate(meshHeart.cells_dict[heartCellShape]):
            f.write("{0:d}, {1:d}, {2:d}, {3:d}, {4:d}\n".format(idx+1, el[0]+1, el[1]+1, el[2]+1, el[3]+1))
        f.write("*Elset, elset=ALL_HEART, generate\n")
        f.write("1, {}, 1\n".format(meshHeart.cells_dict[heartCellShape].shape[0]))   
        f.write("** Section: Section_HEART\n")
        f.write("*Solid Section, elset=ALL_HEART, material=MATERIAL_HEART\n")
        f.write(",\n")     
    f.write("*End Part\n**\n")

    #SCAFFOLD
    f.write("\n**\n")
    f.write("*Part, name=SCAFFOLD\n")
    f.write("*Node\n")
    for idx, n in enumerate(meshScaffold.points):
        f.write("{0:d}, {1:.15f}, {2:.15f}, {3:.15f}\n".format(idx+1, n[0], n[1], n[2]))
    if args.scaffoldSurface:
        f.write("*Element, type=S4\n")
        for idx, el in enumerate(meshScaffold.cells_dict[scaffoldCellShape]):
            f.write("{0:d}, {1:d}, {2:d}, {3:d}, {4:d}\n".format(idx+1, el[0]+1, el[1]+1, el[2]+1, el[3]+1))
        f.write("*Elset, elset=ALL_SCAFFOLD, generate\n")
        f.write("1, {}, 1\n".format(meshScaffold.cells_dict[scaffoldCellShape].shape[0]))   
        f.write("** Section: Section_SCAFFOLD\n")
        f.write("*Shell Section, elset=ALL_SCAFFOLD, material=MATERIAL_SCAFFOLD\n")
        f.write("0.1, 5\n")
    else:
        f.write("*Element, type=C3D4\n")
        for idx, el in enumerate(meshScaffold.cells_dict[scaffoldCellShape]):
            f.write("{0:d}, {1:d}, {2:d}, {3:d}, {4:d}\n".format(idx+1, el[0]+1, el[1]+1, el[2]+1, el[3]+1))
        f.write("*Elset, elset=ALL_SCAFFOLD, generate\n")
        f.write("1, {}, 1\n".format(meshScaffold.cells_dict[scaffoldCellShape].shape[0]))   
        f.write("** Section: Section_SCAFFOLD\n")
        f.write("*Solid Section, elset=ALL_SCAFFOLD, material=MATERIAL_SCAFFOLD\n")
        f.write("\n")
    f.write("*End Part\n**\n**\n")


    f.write("** ASSEMBLY\n**\n")
    f.write("*Assembly, name=Assembly\n**\n")
    f.write("*Instance, name=ScaffoldInstance, part=SCAFFOLD\n")
    f.write("*End Instance\n**\n")
    f.write("*Instance, name=HeartInstance, part=HEART\n")
    f.write("*End Instance\n**\n")
    #Write sets in assembly (or parts?)
    f.write("*Nset, nset=ALL_HEART, instance=HeartInstance, generate\n")
    f.write("1, {}, 1\n".format(meshHeart.points.shape[0]))
    f.write("*Nset, nset=ALL_SCAFFOLD, instance=ScaffoldInstance, generate\n")
    f.write("1, {}, 1\n".format(meshScaffold.points.shape[0]))
    
    for nsetKey in meshScaffold.point_data.keys():
        if nsetKey != "all":
            f.write("*Nset, nset={0}, instance=ScaffoldInstance\n".format(nsetKey))
            nds = [str(i + 1) for i in np.where(meshScaffold.point_data[nsetKey]==1)[0]]
            f.write(
                ",\n".join(",".join(nds[i : i + nnl]) for i in range(0, len(nds), nnl))
                + "\n"
            )
    f.write("*End Assembly\n**\n")
    
    f.write("** MATERIALS\n**\n")
    f.write("*Material, name=MATERIAL_HEART\n")
    f.write("*Elastic\n")
    f.write("200., 0.3\n")
    f.write("*Material, name=MATERIAL_SCAFFOLD\n")
    f.write("*Elastic\n")
    f.write("300.E15, 0.3 \n")

    f.write("** ----------------------------------------------------------------\n")
    f.write("**\n** STEP: Step-1\n**\n")
    f.write("*Step, name=Step-1, nlgeom=NO\n")
    f.write("*Static\n")
    f.write("1., 1., 1e-05, 1.\n**\n")
    f.write("** BOUNDARY CONDITIONS\n**\n")
    f.write("** Name: Heart_Encastre Type: Symmetry/Antisymmetry/Encastre\n")
    f.write("*Boundary\n")
    f.write("ALL_HEART, ENCASTRE\n")

    for key in lmsDiff.keys():
        f.write("** Name: disp_{} Type: Displacement/Rotation\n".format(key))
        f.write("*Boundary\n")
        f.write("{}, 1, 1, {}\n".format(key, lmsDiff[key][0]))
        f.write("{}, 2, 2, {}\n".format(key, lmsDiff[key][1]))
        f.write("{}, 3, 3, {}\n".format(key, lmsDiff[key][2]))
    
    f.write("**\n** OUTPUT REQUESTS\n**\n")
    f.write("*Restart, write, frequency=0\n**\n")
    f.write("** FIELD OUTPUT: F-Output-1\n**\n")
    f.write("*Output, field, variable=PRESELECT\n**\n")
    f.write("** HISTORY OUTPUT: H-Output-1\n**\n")
    f.write("*Output, history, variable=PRESELECT\n")
    f.write("*End Step\n")





