function [] = SaveAbaqus(output_meshfile, nodes, elems, node_sets)
%
% function [] = mat2abaqus(nodes, elems, node_sets, output_meshfile)
%
% mat2abaqus - Reads nodes and elements matrices such as a node_sets cell 
%              if available and writes them in an Abaqus format meshfile 
%
% Syntax:  [] = mat2abaqus(nodes, elems, node_sets, output_meshfile)
%
% INPUT:
%    nodes            - Nodes matrix                          | Format: [nn x 3]
%    elements         - Elements connectivity matrix          | Format: [ee x 4]
%    node_sets        - Node sets cell                        | Format: [ns x {node ids, set_name}] 
%    output_meshfile  - The filepath to store the abaqus mesh | Extension: *.inp
%
% OUTPUT:
%    none 
%
% Example: 
%    not available
%
% Other m-files required: none
% Subfunctions: none
% MAT-files required: none
%
% Author: Konstantinos A. Mountris, Ph.D., Biomedical Engineering
% Université de Bretagne Occidentale, Dept. of Medicine, LaTIM U1101 INSERM
% email address: konstantinos.mountris@gmail.com
% Website: https://www.mountris.org
% May 2018; Last revision: 30-May-2018
%
%%


% Check if filepath is string
if ((ischar(output_meshfile) == 0) && (isstring(output_meshfile) == 0))
    error('File path input required');
end

% Check filepath's extension
[~, ~, ext] = fileparts(output_meshfile);
if (~strcmp(ext,'.inp'))
    error('Abaqus mesh filename should have .inp extension');
end

% Check nodes and elems format
[nodes_num, nodes_dims] = size(nodes);
[elems_num, elems_dims] = size(elems);

if (nodes_num == 0)
    error('Nodes list is empty');
elseif (nodes_dims < 1 || nodes_dims > 3)
    error('Unsupported nodes dimensions. Required nodes with dimensions between 1 and 3')
end

if (elems_num == 0)
    error('Elements list is empty')
end

% Check if node sets have been given
if (nargin == 3)
    node_sets = {};
end

format long g;

% Open output file and write header
fileID = fopen(output_meshfile,'w');
fprintf('Writing to Abaqus mesh file: %s\n',output_meshfile);
fprintf(fileID,'*Heading\n');
fprintf(fileID,'** Job name: Job-1 Model name: Model-1\n');
fprintf(fileID,'** Generated by: Mat2Abaqus.m\n');
fprintf(fileID,'*Preprint, echo=NO, model=NO, history=NO, contact=NO\n');
fprintf(fileID,'**\n** PARTS\n**\n*Part, name=part-1\n');

% Write nodes
fprintf(fileID,'*Node\n');

fprintf('Writing nodes...\n'); 
for nn = 1:nodes_num
    if(nodes_dims == 1)      % 1D
        fprintf(fileID,'%d, %10.15f\n',nn, nodes(nn,:));
    elseif(nodes_dims == 2)  % 2D
        fprintf(fileID,'%d, %10.15f, %10.15f\n',nn, nodes(nn,:));
    else                     % 3D
        fprintf(fileID,'%d, %10.15f, %10.15f, %10.15f\n',nn, nodes(nn,:));
    end
end
fprintf('Wrote %d nodes\n',nodes_num);

% Write elements
fprintf('Writing elements...\n');
if(nodes_dims == 1 && elems_dims == 2)
    fprintf(fileID,'*Element, type=DC1D2, elset=Mesh\n');
elseif(nodes_dims == 2 && elems_dims == 2)
    fprintf(fileID,'*Element, type=DC1D2, elset=Mesh\n');
elseif(nodes_dims == 2 && elems_dims == 3)
    fprintf(fileID,'*Element, type=CPE3, elset=Mesh\n');
elseif(nodes_dims == 3 && elems_dims == 3)
    fprintf(fileID,'*Element, type=CPE3, elset=Mesh\n');
elseif(nodes_dims == 2 && elems_dims == 4)
    fprintf(fileID,'*Element, type=CPE4, elset=Mesh\n');
elseif(nodes_dims == 3 && elems_dims == 2)
    fprintf(fileID,'*Element, type=DC1D2, elset=Mesh\n');
elseif(nodes_dims == 3 && elems_dims == 4)
    fprintf(fileID,'*Element, type=C3D4, elset=Mesh\n');
elseif(nodes_dims == 3 && elems_dims == 8)
    fprintf(fileID,'*Element, type=C3D8, elset=Mesh\n');
else
    error('Cannot write unsupported elements');
end

for el_id = 1:elems_num
    if(elems_dims == 2)        % Line element
        fprintf(fileID,'%d, %d, %d\n',el_id, elems(el_id,:));
    elseif(elems_dims == 3)    % Triangle element
        fprintf(fileID,'%d, %d, %d, %d\n',el_id, elems(el_id,:));
    elseif(elems_dims == 4)    % Quadrilateral or tetrahedron element
        fprintf(fileID,'%d, %d, %d, %d, %d\n',el_id, elems(el_id,:));
    else                       % Hexahedron element
        fprintf(fileID,'%d, %d, %d, %d, %d, %d, %d, %d, %d\n',el_id, elems(el_id,:));
    end
end
fprintf('Wrote %d elements\n',elems_num);

% Write node sets if available
if (isempty(node_sets) == 0)
    
    % Number of node sets
    nsets_num = length(node_sets);
    
    for ns = 1:nsets_num
       fprintf('Writing node set %s...\n',node_sets{ns}{2}); 
       
       fprintf(fileID,'*Nset, nset=%s\n',node_sets{ns}{2});
       
       % Write nodes of node set, 15 per text line
       counter = 0;
       for el_id = 1:size(node_sets{ns}{1},1)
           fprintf(fileID,'%d', node_sets{ns}{1}(el_id) );
           counter = counter + 1;
           
           % Choose delimiter
           if(counter == 15 || el_id == size(node_sets{ns}{1},1))
               fprintf(fileID,'\n');
               counter = 0;
           else
               fprintf(fileID,', ');
           end
           
       end
       fprintf('Wrote node set %s\n',node_sets{ns}{2});
       
    end
    
end

% Finish writing file
fprintf(fileID,'*End Part\n**\n**\n');
fprintf(fileID,'** ASSEMBLY\n**\n');
fprintf(fileID,'*Assembly, name=Assembly\n');
fprintf(fileID,'**\n*Instance, name=Part-1-1, part=Part-1\n');
fprintf(fileID,'*End Instance\n**\n*End Assembly');

fprintf('Wrote successfully Abaqus mesh file: %s\n',output_meshfile);

% Close output file
fclose(fileID);


end










